### ISSUE TITLE
br-ctl versus iproute2

### ISSUE THREAD

**Issue by kbaegis** [gentoo/netifrc#18]
Need a way to reliably do ip link set dev <dev> master <bridge>.  Additional support for multiple route tables (/etc/iproute2/rt_tables) or network namespace support in this util.  Please either document or let me know what the limitations are around these.

**Comment by robbat2** [comment]
Multiple route tables are included in the policy routing example:
https://github.com/gentoo/netifrc/blob/master/doc/net.example.Linux.in#L988

Can you expound on your need to set the dev master?

There is no `netns` support presently, because nobody has said what they want for it (ideally in a new issue, covering just the `netns` needs).

**Comment by robbat2** [comment]
No further response, closing
